name: ci

on:
  push:
    branches:
      - 'feature/official_steamcmd'

jobs:
  docker:
    strategy:
      matrix:
        include:
           - imagename: Dockerfile.stable
             tagname: stable
           - imagename: Dockerfile.devel
             tagname: devel
           - imagename: Dockerfile.staging
             tagname: staging
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.imagename }}
          push: true
          tags: avivace/ror2server:${{ matrix.tagname }}
