name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    strategy:
      matrix:
        include:
          -
            file: Dockerfile
            tags: avivace/ror2server:stable,avivace/ror2server:latest
            build-args: |
              WINE_REL=stable
              WINE_VER=7.0.0.0~focal-1
          -
            file: Dockerfile
            tags: avivace/ror2server:devel
            build-args: |
              WINE_REL=devel
              WINE_VER=7.5~focal-1
          -
            file: Dockerfile
            tags: avivace/ror2server:staging
            build-args: |
              WINE_REL=staging
              WINE_VER=7.5~focal-1
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.file }}
          push: true
          tags: ${{ matrix.tags }}
          build-args: ${{ matrix.build-args }}
